#!/bin/bash
# set -o pipefail is LOAD-BEARING: every build command below pipes to `tail`, and without
# pipefail a failed `mojo build` exits 0 through the pipe. Prime hit exactly this on the 5090
# laptop (2026-08-04): the script printed its own failure signal ("perf code present? 0") and
# still exited 0 with the .so untouched. A build script that reports success on failure is the
# same defect family as the BLOCK_ATTN trap — see docs/the measurement notes.
set -eo pipefail
export PATH=$HOME/.pixi/bin:$PATH
cd "$(cd "$(dirname "$0")" && pwd)"

# ── MODEL PROFILE ────────────────────────────────────────────────────────────
# One .so serves exactly one model: geometry is compile-time (it sizes ABI-visible
# buffers and appears as static layout shapes). So the repo carries every profile and
# the BUILD picks one, instead of a branch per model -- which is what made the
# Muse work unmergeable and left main unable to build the other model at all.
#
# lib/model_config.mojo is GENERATED (gitignored). It is rewritten on every build so a
# stale one cannot silently produce the wrong kernel; the runtime identity check
# (tools/check_model_identity.py) is the second line of defence.
NOMOS_MODEL="gemma4"
_args=()
while [ $# -gt 0 ]; do
  case "$1" in
    --model) NOMOS_MODEL="$2"; shift 2 ;;
    --model=*) NOMOS_MODEL="${1#*=}"; shift ;;
    *) _args+=("$1"); shift ;;
  esac
done
set -- "${_args[@]+"${_args[@]}"}"
PROFILE="lib/model_profiles/$NOMOS_MODEL.mojo"
if [ ! -f "$PROFILE" ]; then
  echo "FATAL: unknown model profile '$NOMOS_MODEL'. Available:" >&2
  ls lib/model_profiles/*.mojo 2>/dev/null | sed 's|.*/||; s|\.mojo$||; s|^|  --model |' >&2
  exit 1
fi
# A profile can be geometrically right and architecturally incomplete. Building one of
# those yields a kernel that RUNS and emits wrong tokens — the worst failure shape we have
# (it manufactures plausible output). Refuse by default; --force-incomplete-profile is for
# the person actively porting the architecture, who knows the output is not yet valid.
_complete=$(sed -nE 's/^alias PROFILE_COMPLETE = ([0-9]+).*/\1/p' "$PROFILE" | head -1)
if [ "${_complete:-1}" = "0" ] && [ "${FORCE_INCOMPLETE:-0}" != "1" ]; then
  echo "FATAL: model profile '$NOMOS_MODEL' is marked INCOMPLETE on this branch." >&2
  sed -n '/STATUS: GEOMETRY-ONLY/,/PROFILE_COMPLETE/p' "$PROFILE" | sed 's/^#\s\?/       /' >&2
  echo "       Building it would produce a kernel that runs and emits WRONG TOKENS." >&2
  echo "       Set FORCE_INCOMPLETE=1 only if you are porting that architecture now." >&2
  exit 1
fi
{
  echo "# GENERATED by refresh_build.sh --model $NOMOS_MODEL -- DO NOT EDIT, DO NOT COMMIT."
  echo "# Source of truth: $PROFILE"
  cat "$PROFILE"
} > lib/model_config.mojo
echo "model profile: $NOMOS_MODEL  ($PROFILE)"
OUT_SO="libnomos_kernel-$NOMOS_MODEL.so"

case "$(uname -m)" in
  aarch64) CUDA_ARCH_DIR="sbsa-linux" ;;
  x86_64)  CUDA_ARCH_DIR="x86_64-linux" ;;
  *) echo "unsupported host architecture: $(uname -m)" >&2; exit 1 ;;
esac

# WHERE CUDA LIVES IS DISCOVERED, NOT ASSUMED. This defaulted to /usr/local/cuda and so it only
# ever built on boxes carrying a SYSTEM CUDA. Since 2026-08-10 pixi.toml declares CUDA itself
# (cuda-cudart-dev / libcublas-dev / cuda-nvcc, target-scoped to linux-64), so the project
# VENDORS its own CUDA in .pixi/envs/default — and this laptop has no system CUDA at all.
# The declaration landed; this consumer kept the old assumption, which is why "the CUDA issue"
# recurred on every fresh build here. Prefer, in order:
#   1. $CUDA_HOME            — an explicit operator override always wins.
#   2. the pixi env          — what the project DECLARES, so the build matches the lockfile.
#   3. /usr/local/cuda       — a system install, for boxes that have one.
# Probe for libcudart rather than for a directory: a path can exist and be empty, and an empty
# -L resolves to nothing at link time with a much worse error than this one.
_has_cudart() { ls "$1/targets/$CUDA_ARCH_DIR/lib"/libcudart.so* >/dev/null 2>&1; }
PIXI_ENV_DIR="$(cd "$(dirname "$0")" && pwd)/.pixi/envs/default"
CUDA_ROOT=""
for _cand in "${CUDA_HOME:-}" "$PIXI_ENV_DIR" "/usr/local/cuda"; do
  [ -n "$_cand" ] || continue
  if _has_cudart "$_cand"; then CUDA_ROOT="$_cand"; break; fi
done
if [ -z "$CUDA_ROOT" ]; then
  echo "FATAL: no libcudart found for $CUDA_ARCH_DIR. Looked in:" >&2
  echo "  \$CUDA_HOME     = ${CUDA_HOME:-<unset>}" >&2
  echo "  pixi env       = $PIXI_ENV_DIR" >&2
  echo "  system         = /usr/local/cuda" >&2
  echo "If the pixi env is the intended source, run 'pixi install' first — the CUDA packages" >&2
  echo "are declared in pixi.toml under [target.linux-64.dependencies]." >&2
  exit 1
fi
CUDA_TARGET_LIB="$CUDA_ROOT/targets/$CUDA_ARCH_DIR/lib"
# Headers split by layout: conda/pixi puts them under targets/<arch>/include, a system CUDA
# puts them at the root. Try both and fail loudly rather than hand gcc a -I that resolves to
# nothing (which surfaces later as an opaque 'unknown type name' inside nomos_cuda_budget.c).
CUDA_INC=""
for _inc in "$CUDA_ROOT/targets/$CUDA_ARCH_DIR/include" "$CUDA_ROOT/include"; do
  [ -f "$_inc/cuda_runtime.h" ] && { CUDA_INC="$_inc"; break; }
done
if [ -z "$CUDA_INC" ]; then
  echo "FATAL: cuda_runtime.h not found under $CUDA_ROOT (needed by nomos_cuda_budget.c)" >&2
  exit 1
fi
echo "CUDA_ROOT=$CUDA_ROOT"
echo "  lib=$CUDA_TARGET_LIB"
echo "  inc=$CUDA_INC"
# Rebuilds the .so on the CURRENT checkout. Does NOT switch branches or hard-reset
# (the old `git checkout fork-refactor && git reset --hard` was a footgun that silently
#  discarded local work — removed 2026-06-25). Check out the branch you want yourself.
echo "=== refresh build on $(git rev-parse --abbrev-ref HEAD 2>/dev/null) @ $(git rev-parse --short HEAD 2>/dev/null) ==="
echo "=== pixi env sync ==="
# `pixi install` is BEST-EFFORT, and the toolchain pin below is the real gate.
#
# Why: compiling this kernel needs mojo + max-core + CUDA, all conda packages. It does NOT
# need the pypi layer (fastapi, pytest, typer...) — those serve the harnesses. But `pixi
# install` validates the WHOLE env, so unrelated pypi drift takes the build down with it.
# Measured 2026-08-15 on this laptop: the env's pypi CONSOLE SCRIPTS (bin/normalizer,
# bin/pytest, bin/httpx, bin/typer, bin/markdown-it) had vanished while every package itself
# was intact, so pixi panicked ("Tokio executor failed") on a file nothing in this build uses.
# A green `pixi install` was never evidence the compiler was right anyway — it is a proxy.
# So: attempt the sync, do not die on it, and then CHECK THE THING THAT ACTUALLY MATTERS,
# which is that mojo is exactly the pinned version. That is a stronger gate than the proxy.
if pixi install 2>&1 | tail -3; then
  PIXI_RUN=(pixi run)
else
  echo "WARN: pixi install failed — falling back to --no-install (existing env)." >&2
  echo "      The toolchain-pin check below decides whether that env is usable." >&2
  PIXI_RUN=(pixi run --no-install)
fi

# HARD GATE on the toolchain, replacing the implicit trust in `pixi install`. A .so built by
# the wrong mojo is the fleet-wide migration hazard: the July pin is a gate, not a preference.
WANT_MOJO="$(sed -nE 's/^mojo = "==(.*)"/\1/p' pixi.toml | head -1)"
GOT_MOJO="$("${PIXI_RUN[@]}" mojo --version 2>/dev/null | sed -nE 's/^Mojo ([^ ]+).*/\1/p' | head -1)"
if [ -z "$GOT_MOJO" ]; then
  echo "FATAL: no usable mojo in the env." >&2; exit 1
fi
if [ -n "$WANT_MOJO" ] && [ "$WANT_MOJO" != "$GOT_MOJO" ]; then
  echo "FATAL: mojo pin mismatch — pixi.toml wants $WANT_MOJO, env has $GOT_MOJO." >&2
  echo "       Refusing to build: the toolchain pin is a fleet-wide gate." >&2
  exit 1
fi
echo "mojo pin OK: $GOT_MOJO"
echo "=== gcc shims ==="
gcc -c -fPIC nomos_libc_shim.c -o nomos_libc_shim.o && gcc -c -fPIC nomos_token_cb_stub.c -o nomos_token_cb_stub.o && gcc -c -fPIC -fvisibility=hidden -I"$CUDA_INC" nomos_cuda_budget.c -o nomos_cuda_budget.o && echo "shims ok"
echo "=== build libnomos_kernel for current GPU ($(date +%T)) ==="
"${PIXI_RUN[@]}" mojo build --emit shared-lib nomos_ffi.mojo -o "$OUT_SO" \
  -Xlinker nomos_libc_shim.o -Xlinker nomos_token_cb_stub.o -Xlinker nomos_cuda_budget.o \
  -Xlinker "-L$CUDA_TARGET_LIB" -Xlinker "-L$CUDA_ROOT/lib" \
  -Xlinker "-rpath" -Xlinker "$CUDA_TARGET_LIB" \
  -Xlinker "-rpath" -Xlinker "$CUDA_ROOT/lib" \
  -Xlinker -lcudart -Xlinker -lcublas -Xlinker -lm 2>&1 | tail -8
echo "=== verify ==="
# Publish the per-model artifact under the generic name LAST, and only after the
# symbol gate below. Building straight to libnomos_kernel.so means a FAILED build
# deletes the working kernel -- which happened on 2026-08-15.
ls -la "$OUT_SO"
readelf -d "$OUT_SO" 2>/dev/null | grep -E "NEEDED.*(cublas|cudart)" || echo "WARN cuda link?"
# HARD GATE, not telemetry: zero exported nomos_ symbols == the build did not produce a usable
# .so, and this script must say so with its exit code (the old `|| true` here swallowed it).
NOMOS_SYMS=$(nm -D "$OUT_SO" 2>/dev/null | grep -c nomos_ || true)
echo "perf code present? $NOMOS_SYMS"
if [ "${NOMOS_SYMS:-0}" -lt 1 ]; then
  echo "BUILD FAILED: no nomos_ symbols exported from $OUT_SO" >&2
  exit 1
fi
cp -f "$OUT_SO" libnomos_kernel.so
echo "published: libnomos_kernel.so  <- $OUT_SO"
echo "=== REFRESH BUILD DONE $(date) ==="
