"""Dump gdn_recurrent_scan_kernel outputs for a DETERMINISTIC input, for numpy comparison.

Independent-ground-truth gate: the trainer's GDN backward is derived against a numpy transcription
of this recurrence, and a gradcheck only proves that backward is consistent with THAT transcription.
If the transcription itself is wrong, both agree and both are wrong. So the reference forward is
compared here against the SHIPPED kernel on identical inputs.

Inputs are generated by an explicit LCG so the numpy side can reproduce them bit-for-bit without
transferring a file. Writes raw fp32 to the paths given in argv.
"""
from max.gpu.host import DeviceContext
from lib.cuda import cuda_malloc, cuda_free, cuda_upload, cuda_upload_u16, cuda_download, cuda_sync
from lib.gdn_scan import gpu_gdn_recurrent_scan
from lib.model_profiles.qwen3_5 import (
    GDN_CONV_DIM, GDN_VALUE_DIM, GDN_NUM_V_HEADS, GDN_KEY_DIM,
)
from std.os import getenv


def lcg_fill(n: Int, seed: UInt64, lo: Float32, hi: Float32) -> List[Float32]:
    """Deterministic values reproducible in numpy: x = (a*x + c) mod 2^32, scaled into [lo, hi)."""
    var out = List[Float32](capacity=n)
    var st = seed
    for _ in range(n):
        st = (st * 1664525 + 1013904223) % 4294967296
        var u = Float32(st) / Float32(4294967296.0)
        out.append(lo + (hi - lo) * u)
    return out^


def main() raises:
    var ctx = DeviceContext()
    var S = Int(atol(getenv("GDN_S", "6")))

    var qkv = lcg_fill(S * GDN_CONV_DIM, 12345, -1.0, 1.0)
    var g = lcg_fill(S * GDN_NUM_V_HEADS, 777, -1.0, 0.0)      # log-decay <= 0
    var beta = lcg_fill(S * GDN_NUM_V_HEADS, 999, 0.0, 1.0)

    var d_qkv = cuda_malloc(S * GDN_CONV_DIM * 4)
    var d_g = cuda_malloc(S * GDN_NUM_V_HEADS * 4)
    var d_beta = cuda_malloc(S * GDN_NUM_V_HEADS * 4)
    var d_out = cuda_malloc(S * GDN_VALUE_DIM * 4)
    # recurrent state starts at ZERO so the numpy side needs no state transfer
    var nstate = GDN_NUM_V_HEADS * 128 * 128
    var d_state = cuda_malloc(nstate * 2)
    var zstate = List[UInt16](capacity=nstate)
    for _ in range(nstate):
        zstate.append(0)
    cuda_upload_u16(d_state, zstate)

    cuda_upload(d_qkv, qkv)
    cuda_upload(d_g, g)
    cuda_upload(d_beta, beta)

    gpu_gdn_recurrent_scan(ctx, d_out, d_qkv, d_g, d_beta, d_state, S)
    ctx.synchronize()
    cuda_sync()

    var host = List[Float32](capacity=S * GDN_VALUE_DIM)
    for _ in range(S * GDN_VALUE_DIM):
        host.append(0.0)
    cuda_download(host, d_out, len(host))

    print("S", S, "CONV_DIM", GDN_CONV_DIM, "VALUE_DIM", GDN_VALUE_DIM,
          "NVH", GDN_NUM_V_HEADS, "KEY_DIM", GDN_KEY_DIM)
    # print a deterministic slice for comparison (first 8 of the first 3 rows)
    for t in range(3 if S >= 3 else S):
        var line = String("ROW ") + String(t)
        for c in range(8):
            line += String(" ") + String(host[t * GDN_VALUE_DIM + c])
        print(line)
    cuda_free(d_qkv); cuda_free(d_g); cuda_free(d_beta); cuda_free(d_out); cuda_free(d_state)
